### PR TITLE
Extension Usage

### PR DESCRIPTION
**Pull request by danrye**
Curious what you think of this usage, would you consider adding this?

### CODE REVIEW

**Comment by tractorcow** [comment]
I don't think it would work because `Tag` isn't a class that's included in this module, I'm afraid. :P

**Comment by danrye** [comment]
Right, they had to create that before, but it minimizes what a dev has to bring to the table.  Just a thought.  You could include tag, but then they'd have to extend tag to implement the belongs_many and tag is so simple it didn't seem worth it. 



—

**Comment by dhensby** [comment]
I think including this in the docs is helpful, but including the Extension doesn't make sense if the dependencies don't exist.

**Comment by dhensby** [comment]
:+1:

**Comment by dhensby** [comment]
No movement on this in 1.5 years - closing.

**Pull request closed without merging**
