### PR TITLE
Add css and js to left and main

### PR DESCRIPTION
**Pull request by thats4shaw**
* Add yaml file
* Remove requirement calls from field constructors

### CODE REVIEW

**Comment by thats4shaw** [comment]
Fixes https://github.com/silverstripe/silverstripe-tagfield/issues/129.

**Comment by robbieaverill** [comment]
We'd need to be careful - technically renaming the config block could be a breaking change if people are doing their own config `After: tagfield`

**Comment by ScopeyNZ** [comment]
It's a new config block though?

**Comment by robbieaverill** [comment]
Right - I only looked at the diff

**Pull request merged**
